### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by pushred** [javve/list.js#235] opened 2014-04-16 00:49 UTC
There's great support for RequireJS and Component, but how about [Browserify][browserify]? The readme lists support for CommonJS, but even though List.js is composed of CommonJS modules it's dependent upon Component packages and component(1). So close, yet _so far_ :sweat_smile: Totally respect the decision to use Component, but it's pretty opinionated. Since I can load List.js standalone I think it's just an issue with the structure of the code that's preventing it from working with Browserify.

I'd love to be able to at least add List.js as a Bower dependency and require `/dist/list.js` with Require (shimming the global as necessary), but I run into this:

> Error: module "get-by-class" not found from "/node_modules/list.js/index.js"

Of course that's just because I'm missing the build step with Component to pull down your dependencies. One route I could go is to use the [decomponentify][decomponentify] transform. But I'd still need to add Component as a dependency for my project and a build step.

Just wanted to put this on your radar if it wasn't already!

[browserify]: http://browserify.org
[decomponentify]: https://github.com/eugeneware/decomponentify

**Comment by fabien-h** [comment] 2015-04-10 13:28
any news on that one ?

**Comment by ryangiglio** [comment] 2015-11-19 16:58
Good news - this is coming in the next version, whenever that may be https://github.com/javve/list.js/issues/271#issuecomment-100679229

**Comment by javve** [comment] 2016-02-26 19:59
Yep, this will be included in the next version (which is actually getting closer and closer!). Duplicate of #235

**Closed by javve** 2016-02-26 19:59 UTC
