### ISSUE TITLE
Creating a dynamic table with a template fails in getElementsByClassName

### ISSUE THREAD

**Issue by rdpoor** [javve/list.js#403] opened 2016-04-07 20:52 UTC
I'm getting

    Uncaught TypeError: Cannot read property 'getElementsByClassName' of null   list.js:1111

when creating a List using an empty 

    <table><tbody class="list"></tbody></table> 

as the List's container.

The error appears not at the first call to getElementsByClass, but at the second, when it's setting up the template.

Very simple pen in http://codepen.io/fearless_fool/pen/eZyEJm?editors=1111, modeled after http://codepen.io/javve/pen/oEezp -- the only difference is that there's no pre-defined entries, and it uses an `item:` template.

FWIW, I'm using Chrome Version 49.0.2623.110 (64-bit).

Can you reproduce this?  Is there a workaround?

**Comment by rdpoor** [comment] 2016-04-07 23:32
I should mention that the same code does work if you change out the table with 

    <ul class="list"></ul>

and make appropriate changes to the `item:` template.

**Comment by rdpoor** [comment] 2016-04-07 23:45
There is a rather obvious workaround using CSS:

    .table {
        display: table;
        width: 100%;
    }
    .tr {
        display: table-row;
    }
    .td {
        display: table-cell;
    }

and js:

    var options = {
        valueNames: ['name','born'],
        item: '<div class="tr"><div class="td name"></div><div class="td born"></div></div>',
    };

and html:

        <div id="users">
          ...
          <div class="table list"></div>
        </div>

**Comment by lukeed** [comment] 2016-04-26 19:17
Ran into same issue.

I can even do:

```js
var options = {
  valueNames: [ 'name', 'born' ],
  item: '<li><h3 class="name"></h3><p class="born"></p></li>'
}
```

and have that appended to: `<tbody class="list"></tbody>`

The issue occurs as soon as you switch `li` for `tr`, then you end up with the `getElementsByClassName` error above, or `cloneNode of null`

**Comment by lukeed** [comment] 2016-04-26 19:54
Relevant [code location](https://github.com/javve/list.js/blob/master/src/templater.js#L44)

**Comment by muth02446** [comment] 2016-06-02 11:47
I also ran into this. Hopefully the fix will be merged soon. It would also be nice to and an example that starts with a complete empty table just like there are examples that start with an empty list.

**Comment by AlexisTM** [comment] 2016-10-21 07:52
I still have the exact same issue using the template system with a table.

HTML
```html
<table>
  <tbody class="list">
  </tbody>
</table>
```

JS options
```javascript
var options = {
  valueNames: [ 'index', 'born' ],
  item:'<tr><td class="index"></td> <td class="born"></td></tr>' // NOT working
  // item: '<li> <h3 class="index"></h3><h3 class="born"></h3></li>' // Working
};
```

Example :
http://codepen.io/AlexisTM/pen/ozJBAg

**Comment by lukeed** [comment] 2016-10-21 07:56
@AlexisTM I have a PR (#412) open for months (!) now that fixes it. Check the commit if you want to manually apply it to your local copy.

**Comment by AlexisTM** [comment] 2016-10-21 08:07
It is also to show the problem is still active and the PR is needed. I'll manually fix it from your repo. Thanks for the PR @lukeed :D

**Closed** 2016-10-22 19:50 UTC
