### ISSUE TITLE
Sorting breaks when listObj is created from .js file

### ISSUE THREAD

**Issue by hallaathrad** [javve/list.js#441] opened 2016-08-17 17:50 UTC
It's such an odd bug and I haven't been able to figure out why it happens, but when you do
```
var listObj = new List('whatever', options);
```
from an included file rather than inside a script tag inside the same html file, the sort buttons only work the first time. When clicked afterwards said button doesn't toggle the list to the opposite order. Any ideas why?

**Comment by cscuderi** [comment] 2016-08-24 20:14
I had something similar happen to me. What was happening was the sort was being toggled twice on click. I was able to track down where the second sort was happening and remove it. Are the classes (`asc` and `desc`) being added to the sort button when it's clicked?

**Comment by hallaathrad** [comment] 2016-08-24 20:21
No, it doesn't change the class at all, it seems. It's very strange... however, I did notice the JS external file is being loaded twice (thanks to rails stupid way of handling assets), which would load the `var listObj` twice. But that by itself should not cause such a weird glitch, specifically with sorting... everything else works just fine.

**Comment by javve** [comment] 2016-10-15 09:18
This seems like a duplicate of https://github.com/javve/list.js/issues/316
I'll have a look at that bug!

**Closed by javve** 2016-10-15 09:18 UTC
