### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by Atulin** [javve/list.js#609] opened 2018-07-10 18:54 UTC
- **117** open issues, dating back to **17 Jan 2013**
 - **23** awaiting pull requests dating back to **19 Jul 2013**
 - Last release **29 Jan 2017**
 - Last commit **21 Jun 2017**

Perhaps a fork is in order? Or adding some contributors to take care of this repo if the owner is unwilling to?

**Comment by davidlesieur** [comment] 2018-07-12 20:08
This is a duplicate of #582.

**Comment by wowcut** [comment] 2018-08-14 21:58
Please answer this important question.

**Comment by Atulin** [comment] 2018-08-14 22:30
I think a lack of answer is an answer enough ¯\\\_(ツ)_/¯

**Comment by javve** [comment] 2018-12-16 21:12
Sorry about the lack of activity. List.js have been sleeping for a while but it's not dead. 

I'll do my best to make some updates during xmas. I appreciate your concern ❤️

**Closed** 2018-12-16 21:13 UTC
