### ISSUE TITLE
Sort by data attribute

### ISSUE THREAD

**Issue by skatenerd** [javve/list.js#226] opened 2014-03-19 16:02 UTC
Is it possible to sort a list by data attributes of its elements?
I could write a custom sort function, but is there a simpler recommended way?

**Comment by dickieirwin** [comment] 2015-02-26 03:52
Sorting by data attributes would be a great feature.

**Comment by javve** [comment] 2016-02-26 21:11
This I'll (finally!) be added in the next version that is coming out soon!
Duplicate of #35.

**Closed by javve** 2016-02-26 21:11 UTC
